### ISSUE TITLE
High level schema design

### ISSUE THREAD

**Issue by suntong** [knq/xo#32]
Viewing from a very high level, what xo currently does, is basically reverse-engine physical designs from the database to generate code. 

What I hope is, someday xo can start not from reverse-engine physical databases, but from schema high level designs. 

Take this ER diagram for example (taken from http://symfony.com/legacy/doc/askeet/1_0/en/2), 

![ER diagram](http://symfony.com/legacy/images/askeet/1_0/mcd1.gif)

It can be expressed in high level in something like this (taken from http://symfony.com/legacy/doc/askeet/1_0/en/2):

```yaml
propel:
  _attributes:   { noXsd: false, defaultIdMethod: none, package: lib.model }
 
  ask_question:
    _attributes: { phpName: Question, idMethod: native }
    id:          { type: integer, required: true, primaryKey: true, autoIncrement: true }
    user_id:     { type: integer, foreignTable: ask_user, foreignReference: id }
    title:       { type: longvarchar }
    body:        { type: longvarchar }
    created_at:  ~
    updated_at:  ~
 
  ask_answer:
    _attributes: { phpName: Answer, idMethod: native }
    id:          { type: integer, required: true, primaryKey: true, autoIncrement: true }
    question_id: { type: integer, foreignTable: ask_question, foreignReference: id }
    user_id:     { type: integer, foreignTable: ask_user, foreignReference: id }
    body:        { type: longvarchar }
    created_at:  ~
 
  ask_user:
    _attributes: { phpName: User, idMethod: native }
    id:          { type: integer, required: true, primaryKey: true, autoIncrement: true }
    nickname:    { type: varchar(50), required: true, index: true }
    first_name:  varchar(100)
    last_name:   varchar(100)
    created_at:  ~
 
  ask_interest:
    _attributes: { phpName: Interest, idMethod: native }
    question_id: { type: integer, foreignTable: ask_question, foreignReference: id, primaryKey: true }
    user_id:     { type: integer, foreignTable: ask_user, foreignReference: id, primaryKey: true }
    created_at:  ~
 
  ask_relevancy:
    _attributes: { phpName: Relevancy, idMethod: native }
    answer_id:   { type: integer, foreignTable: ask_answer, foreignReference: id, primaryKey: true }
    user_id:     { type: integer, foreignTable: ask_user, foreignReference: id, primaryKey: true }
    score:       { type: integer }
    created_at:  ~
```

The syntax details is irrelevant, but my point is that YAML can express the tables, PK, FK, and relationships very clearly, in very high level. The physical design, and implementation details should be left to the code gen. 

Just a wish.

**Comment by kenshaw** [comment]
This is not likely to ever happen. This would require writing a parser that understands that syntax, and then writing the SQL for all the different databases supported by xo.

**Comment by kenshaw** [comment]
To expand on the above -- currently the flow for xo is like this:
```
sql schema -> xo -> go
```
What you're essentially asking for is a tool that does this:
```
relationship diagram -> xo -> SQL (for schema creation)
```
As you can see, that doesn't really fit into the specific use case for xo. In my opinion, a separate tool would be better for this purpose, and then use the schema generated by that tool with xo to generate go.

**Comment by suntong** [comment]
NP. 

I'll try to read into xo's code and see what I can do. So, 

- If I send in patches, would it ever be accepted? 
- else, if I build another package on top of xo, and need xo to expose some of the internal stuff, would that be OK with you? 

FTR, I like this syntax better (taken from http://symfony.com/legacy/doc/tutorial/1_0/en/doctrine-my-first-project)

```yaml
Post:
  actAs: [Timestampable, Sluggable]
  columns:
    title: string(255)
    excerpt: string
    body: clob

Comment:
  actAs: [Timestampable]
  columns:
    post_id: integer
    author: string(255)
    email: string(255)
    body: clob
  relations:
    Post:
      onDelete: CASCADE
      foreignAlias: Comments
```
